/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminDeitiesRouteImport } from './routes/admin.deities'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as DeitySlugRouteImport } from './routes/deity.$slug'
import { Route as MantraSlugRouteImport } from './routes/mantra.$slug'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as SignUpSplatRouteImport } from './routes/sign-up.$'
import { Route as AdminEditorSlugRouteImport } from './routes/admin.editor.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDeitiesRoute = AdminDeitiesRouteImport.update({
  id: '/admin/deities',
  path: '/admin/deities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DeitySlugRoute = DeitySlugRouteImport.update({
  id: '/deity/$slug',
  path: '/deity/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MantraSlugRoute = MantraSlugRouteImport.update({
  id: '/mantra/$slug',
  path: '/mantra/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpSplatRoute = SignUpSplatRouteImport.update({
  id: '/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEditorSlugRoute = AdminEditorSlugRouteImport.update({
  id: '/admin/editor/$slug',
  path: '/admin/editor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deities': typeof AdminDeitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/deity/$slug': typeof DeitySlugRoute
  '/mantra/$slug': typeof MantraSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/editor/$slug': typeof AdminEditorSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deities': typeof AdminDeitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/deity/$slug': typeof DeitySlugRoute
  '/mantra/$slug': typeof MantraSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin': typeof AdminIndexRoute
  '/admin/editor/$slug': typeof AdminEditorSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/deities': typeof AdminDeitiesRoute
  '/api/health': typeof ApiHealthRoute
  '/deity/$slug': typeof DeitySlugRoute
  '/mantra/$slug': typeof MantraSlugRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/sign-up/$': typeof SignUpSplatRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/editor/$slug': typeof AdminEditorSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/saved'
    | '/search'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/deities'
    | '/api/health'
    | '/deity/$slug'
    | '/mantra/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/editor/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/saved'
    | '/search'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/deities'
    | '/api/health'
    | '/deity/$slug'
    | '/mantra/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin'
    | '/admin/editor/$slug'
  id:
    | '__root__'
    | '/'
    | '/saved'
    | '/search'
    | '/admin/analytics'
    | '/admin/dashboard'
    | '/admin/deities'
    | '/api/health'
    | '/deity/$slug'
    | '/mantra/$slug'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/admin/'
    | '/admin/editor/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDeitiesRoute: typeof AdminDeitiesRoute
  ApiHealthRoute: typeof ApiHealthRoute
  DeitySlugRoute: typeof DeitySlugRoute
  MantraSlugRoute: typeof MantraSlugRoute
  SignInSplatRoute: typeof SignInSplatRoute
  SignUpSplatRoute: typeof SignUpSplatRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditorSlugRoute: typeof AdminEditorSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/deities': {
      id: '/admin/deities'
      path: '/admin/deities'
      fullPath: '/admin/deities'
      preLoaderRoute: typeof AdminDeitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deity/$slug': {
      id: '/deity/$slug'
      path: '/deity/$slug'
      fullPath: '/deity/$slug'
      preLoaderRoute: typeof DeitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mantra/$slug': {
      id: '/mantra/$slug'
      path: '/mantra/$slug'
      fullPath: '/mantra/$slug'
      preLoaderRoute: typeof MantraSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up/$': {
      id: '/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof SignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editor/$slug': {
      id: '/admin/editor/$slug'
      path: '/admin/editor/$slug'
      fullPath: '/admin/editor/$slug'
      preLoaderRoute: typeof AdminEditorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDeitiesRoute: AdminDeitiesRoute,
  ApiHealthRoute: ApiHealthRoute,
  DeitySlugRoute: DeitySlugRoute,
  MantraSlugRoute: MantraSlugRoute,
  SignInSplatRoute: SignInSplatRoute,
  SignUpSplatRoute: SignUpSplatRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditorSlugRoute: AdminEditorSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
